# Generated by Django 5.0.7 on 2024-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadStudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=12, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_period',
            field=models.CharField(max_length=50, verbose_name='Periodo do Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='CadStudent.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='CadStudent/', verbose_name='Foto do estudante'),
        ),
    ]
