# Generated by Django 5.0.7 on 2024-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadStudent', '0002_alter_student_age_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(max_length=12, verbose_name='Data de nascimento'),
        ),
    ]
